### ISSUE TITLE
Raygun.Logger failing

### ISSUE THREAD

**Issue by RobinClowers** [Cobenian/raygun#14]
I'm not sure what to make of this stack trace, but it only happens when I include `Raygun.Logger` in my logger backends.

```
[error] GenEvent handler Raygun.Logger installed at Logger
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Poison.Encoder.List."-encode/3-lists^foldr/2-1-"/3
        (poison) lib/poison/encoder.ex:233: Poison.Encoder.List."-encode/3-lists^foldr/2-1-"(#Function<1.65720235/2 in Poison.Encoder.List.encode/3>, [], "** (exit) an exception was raised:\n    ** (MatchError) no match of right hand side value: {:error, 404}\n        (booking) web/queries/get_hotel_details.ex:13: Booking.Queries.GetHotelDetails.execute/1\n        (booking) web/controllers/api/hotel_controller.ex:2: Booking.Api.HotelController.show/2\n        (booking) web/controllers/api/hotel_controller.ex:1: Booking.Api.HotelController.action/2\n        (booking) web/controllers/api/hotel_controller.ex:1: Booking.Api.HotelController.phoenix_controller_pipeline/2\n        (booking) lib/phoenix/router.ex:261: Booking.Router.dispatch/2\n        (booking) web/router.ex:1: Booking.Router.do_call/2\n        (booking) lib/booking/endpoint.ex:1: Booking.Endpoint.phoenix_pipeline/1\n        (booking) lib/booking/endpoint.ex:1: Booking.Endpoint.call/2")
        (poison) lib/poison/encoder.ex:233: Poison.Encoder.List."-encode/3-lists^foldr/2-1-"/3
        (poison) lib/poison/encoder.ex:233: Poison.Encoder.List."-encode/3-lists^foldr/2-1-"/3
        (poison) lib/poison/encoder.ex:233: Poison.Encoder.List.encode/3
        (poison) lib/poison/encoder.ex:213: anonymous fn/4 in Poison.Encoder.Map.encode/3
        (poison) lib/poison/encoder.ex:214: Poison.Encoder.Map."-encode/3-lists^foldl/2-0-"/3
        (poison) lib/poison/encoder.ex:214: Poison.Encoder.Map.encode/3
        (poison) lib/poison/encoder.ex:213: anonymous fn/4 in Poison.Encoder.Map.encode/3
[error] GenEvent handler Raygun.Logger installed in Logger terminating
```

**Comment by RobinClowers** [comment]
``` elixir
  "poison": {:hex, :poison, "1.5.2"},
  "raygun": {:hex, :raygun, "0.2.0"},
```

**Comment by larskrantz** [comment]
I'm guessing it's the same as issue #17
